In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt
import xlsxwriter

In [4]:
df = pd.read_excel('Alarmes.xlsx')

In [5]:
df.head()

,Alarm Severity,Alarm Name,Device Type,Device Name,PV Plant,Generated On,Cleared On,Clearance Type,Alarm ID,Location Information
0,Minor,Communication Fault\t,SUN2000,INDIANS_5kW_1\t,Indians\t,2019-06-13 07:41:07\t,2019-06-13 07:45:03\t,Automatic clear,999999999,NaN
1,Minor,Communication Fault\t,SUN2000,Fetter_5kW\t,Robinson_Fetter\t,2019-06-13 04:52:30\t,2019-06-13 05:04:04\t,Automatic clear,999999999,NaN
2,Minor,Communication Fault\t,SUN2000,Fetter_5kW\t,Robinson_Fetter\t,2019-06-13 02:34:32\t,2019-06-13 03:02:53\t,Automatic clear,999999999,NaN
3,Minor,Communication Fault\t,SUN2000,Fetter_3kW\t,Robinson_Fetter\t,2019-06-13 02:32:22\t,2019-06-13 03:59:01\t,Automatic clear,999999999,NaN
4,Minor,Communication Fault\t,SUN2000,Glaucio_Lipski\t,Glaucio Lipski\t,2019-06-13 01:09:48\t,2019-06-13 01:16:20\t,Automatic clear,999999999,NaN

In [35]:
Betine_Rost = df[df['PV Plant'] == 'Betine_Rost\t']
Cassio_Burin = df[df['PV Plant']== 'Cassio_Burin\t']
Rosa_Radunz = df[df['PV Plant']== 'Rosa_Radunz\t']
Fabio_Moura = df[df['PV Plant'] == 'Fabio_Moura\t']
Glaucio_Lipski = df[df['PV Plant'] == 'Glaucio Lipski\t']
Indians = df[df['PV Plant'] == 'Indians\t']
Jose_Morais = df[df['PV Plant'] =='Jose_Morais\t']
Cristiano_Anschau = df[df['PV Plant'] == 'Cristiano Anschau\t']
Daniela_Massalai = df[df['PV Plant'] == 'Daniela_Massalai\t']
Eldo_Rost = df[df['PV Plant'] == 'Eldo Rost\t']
Ivo_Oliveira = df[df['PV Plant'] == 'Ivo_Oliveira\t']
Luciana_Correa = df[df['PV Plant'] =='Luciana Correa\t']
Marcio_Siqueira = df[df['PV Plant'] == 'Marcio Siqueira\t']
Marcos_Kessler = df[df['PV Plant'] == 'Marcos_ Kessler\t']
Mauricio_Lunardi = df[df['PV Plant'] == 'Mauricio_Lunardi\t']
Cleci_Rubi = df[df['PV Plant'] == 'Cleci_Rubi\t']
Robinson_Fetter = df[df['PV Plant'] == 'Robinson_Fetter\t']
Silvio_Avila = df[df['PV Plant'] == 'Silvio_Avila\t']
Vita_Fisio = df[df['PV Plant'] == 'Vita Fisio\t']
toda = df

In [60]:
exceldados = pd.ExcelWriter('Analise.xlsx',
                            engine='xlsxwriter',
                            datetime_format='mmm-d-yyyy hh:mm:ss',
                            date_format='mmmm-dd-yyyy',)
Betine_Rost.to_excel(exceldados, sheet_name='Betine_Rost')
Cassio_Burin.to_excel(exceldados, sheet_name='Cassio_Burin')
Rosa_Radunz.to_excel(exceldados, sheet_name='Rosa_Radunz')
Fabio_Moura.to_excel(exceldados, sheet_name='Fabio_Moura')
Glaucio_Lipski.to_excel(exceldados, sheet_name='Glaucio_Lipski')
Indians.to_excel(exceldados, sheet_name='Indians')
Jose_Morais.to_excel(exceldados, sheet_name='Jose_Morais')
Cristiano_Anschau.to_excel(exceldados, sheet_name='Cristiano_Anschau')
Daniela_Massalai.to_excel(exceldados, sheet_name='Daniela_Massalai')
Eldo_Rost.to_excel(exceldados, sheet_name='Eldo_Rost')
Ivo_Oliveira.to_excel(exceldados, sheet_name='Ivo_Oliveira')
Luciana_Correa.to_excel(exceldados, sheet_name='Luciana_Correa')
Marcio_Siqueira.to_excel(exceldados, sheet_name='Marcio_Siqueira')
Marcio_Siqueira.to_excel(exceldados, sheet_name='Marcos_Kessler')
Marcos_Kessler.to_excel(exceldados, sheet_name='Marcos_Kessler')
Mauricio_Lunardi.to_excel(exceldados, sheet_name='Mauricio_Lunardi')
Cleci_Rubi.to_excel(exceldados, sheet_name='Cleci_Rubi')
Robinson_Fetter.to_excel(exceldados, sheet_name='Robinson_Fetter')
Silvio_Avila.to_excel(exceldados, sheet_name='Silvio_Avila')
Vita_Fisio.to_excel(exceldados, sheet_name='Vita_Fisio')
exceldados.save()

In [61]:
from win32com.client import Dispatch

appexcel = Dispatch('Excel.Application')
wb = appexcel.Workbooks.Open('C:\\temp\\dev\\TabelasNovas\\Analise.xlsx')

for i in range (1, 20, 1):
    appexcel.Worksheets(i).Activate()
    appexcel.ActiveSheet.Columns.AutoFit()

appexcel.Worksheets(1).Activate()
wb.Save()
wb.Close()