In [2]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
import numpy as np
import matplotlib.pyplot as plt

In [14]:
medidas_dataset = pd.read_excel('medidas01.xls')
medidas_dataset.head() #.T = Transposição de dados.

,Data,Fases,Tensão (Vac),Corrente (A),Fat.Pot.,Pot.Aparente (kVA),Pot.Ativa (kW),Pot.Reativa (kVAr),Falta KVAr,KWh,KWh Ponta,KVArh,KVArh Ponta,Exc. KVAr
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-07-07 05:05:10,R:,221.25,1.57,0.16,0.34,0.05,0.34,0,0,0,0,0,0.20675
2,NaN,S:,218.48,1.45,0.03,0.31,0,0.31,0,0,0,0,0,0.192495
3,NaN,T:,218.7,1.55,0.32,0.33,0.1,0.32,0,0,0,0,0,0.188306
4,NaN,Tot:,NaN,NaN,0.17,0.99,0.17,0.98,0,0,0,0,0,0.590421

In [13]:
medidas_dataset['Falta KVAr'].

TypeError: '>=' not supported between instances of 'int' and 'str'