In [1]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
import numpy as np
import matplotlib.pyplot as plt
import math as mt
fp_padrao = 0.92
fp_padrao_Sup = 2-fp_padrao

In [8]:
ValoresDataset = pd.read_excel('Analise.xlsx', 'Valores')
Valores = ValoresDataset
Valores

,Data,MARLON ROGER COLOVINI,MARLON ROGER COLOVINI.1,MARA REGINA BARICHELLO DA SILVA,JANDIRA TEIXEIRA DUTRA,LUIS FERNANDO KRUGER,PAULO OSCAR BOHN,PAULO OSCAR BOHN.1,PAULO OSCAR BOHN.2,PAULO OSCAR BOHN.3,...,ERNANI MOACIR CZAPLA.1,CARLOS WALMIR LARSAO ROLIM.1,DANIELI MISSIO,Linho Lev Alimentos,Silvio Robert Lemos √Åvila,Valesca da Luz,Olavo Mildner,Dilnei Rohled,Shaiana Signorini,Fonse Atacado
0,jan/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,fev/18,32.58,134.40,35.64,27.63,NaN,48.60,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,mar/18,33.74,73.68,38.49,31.71,48.73,62.93,23.49,122.86,45.43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,abr/18,36.00,55.34,35.21,41.62,65.08,63.05,27.04,67.69,82.53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mai/18,37.34,66.02,64.36,106.90,127.00,64.25,28.41,120.66,115.82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,jun/18,40.09,107.18,68.3,97.41,146.86,64.88,NaN,129.52,103.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,jul/18,53.15,248.94,78.89,91.23,272.91,108.14,51.12,147.69,100.27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ago/18,57.40,122.15,52.21,104.33,153.49,74.60,NaN,147.13,100.88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,set/18,51.04,163.11,54.44,99.83,138.20,72.47,NaN,166.52,126.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,out/18,41.71,105.99,51.94,90.59,85.40,66.23,33.24,70.78,68.60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,nov/18,42.02,100.01,52.32,76.96,89.25,74.12,36.82,103.10,69.37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,dez/18,45.18,81.77,55.39,50.37,79.91,76.49,70.88,59.19,60.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,jan/19,49.25,132.03,"247,76",107.67,155.28,91.61,NaN,184.57,108.38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,fev/19,53.72,133.76,136.76,103.10,175.43,102.11,75.57,223.75,130.07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,mar/19,46.67,80.53,NaN,92.15,91.09,91.47,NaN,155.07,121.65,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,abr/19,44.70,78.40,135.93,75.84,71.42,79.27,67.94,147.76,96.32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,mai/19,46.59,65.14,150.79,119.82,231.68,114.94,42.36,194.89,126.58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,jun/19,NaN,65.37,122.69,110.22,221.84,112.77,44.83,131.62,100.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,jul/19,89.90,73.81,111.22,113.58,156.17,78.18,109.58,144.14,106.44,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,ago/19,54.67,101.76,52.45,99.27,188.77,99.26,121.65,170.08,71.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,set/19,49.82,86.15,54.13,67.74,117.13,85.61,74.11,118.70,38.25,...,NaN,76.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,out/19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,nov/19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,dez/19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,jan/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,fev/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,mar/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,abr/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,mai/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,jun/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,jul/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,ago/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,set/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,out/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,nov/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,dez/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
Valores

,Data,MARLON ROGER COLOVINI,MARLON ROGER COLOVINI.1,MARA REGINA BARICHELLO DA SILVA,JANDIRA TEIXEIRA DUTRA,LUIS FERNANDO KRUGER,PAULO OSCAR BOHN,PAULO OSCAR BOHN.1,PAULO OSCAR BOHN.2,PAULO OSCAR BOHN.3,...,ERNANI MOACIR CZAPLA.1,CARLOS WALMIR LARSAO ROLIM.1,DANIELI MISSIO,Linho Lev Alimentos,Silvio Robert Lemos √Åvila,Valesca da Luz,Olavo Mildner,Dilnei Rohled,Shaiana Signorini,Fonse Atacado
0,jan/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,fev/18,32.58,134.40,35.64,27.63,NaN,48.60,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,mar/18,33.74,73.68,38.49,31.71,48.73,62.93,23.49,122.86,45.43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,abr/18,36.00,55.34,35.21,41.62,65.08,63.05,27.04,67.69,82.53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mai/18,37.34,66.02,64.36,106.90,127.00,64.25,28.41,120.66,115.82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,jun/18,40.09,107.18,68.3,97.41,146.86,64.88,NaN,129.52,103.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,jul/18,53.15,248.94,78.89,91.23,272.91,108.14,51.12,147.69,100.27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ago/18,57.40,122.15,52.21,104.33,153.49,74.60,NaN,147.13,100.88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,set/18,51.04,163.11,54.44,99.83,138.20,72.47,NaN,166.52,126.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,out/18,41.71,105.99,51.94,90.59,85.40,66.23,33.24,70.78,68.60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,nov/18,42.02,100.01,52.32,76.96,89.25,74.12,36.82,103.10,69.37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,dez/18,45.18,81.77,55.39,50.37,79.91,76.49,70.88,59.19,60.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,jan/19,49.25,132.03,"247,76",107.67,155.28,91.61,NaN,184.57,108.38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,fev/19,53.72,133.76,136.76,103.10,175.43,102.11,75.57,223.75,130.07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,mar/19,46.67,80.53,NaN,92.15,91.09,91.47,NaN,155.07,121.65,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,abr/19,44.70,78.40,135.93,75.84,71.42,79.27,67.94,147.76,96.32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,mai/19,46.59,65.14,150.79,119.82,231.68,114.94,42.36,194.89,126.58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,jun/19,NaN,65.37,122.69,110.22,221.84,112.77,44.83,131.62,100.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,jul/19,89.90,73.81,111.22,113.58,156.17,78.18,109.58,144.14,106.44,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,ago/19,54.67,101.76,52.45,99.27,188.77,99.26,121.65,170.08,71.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,set/19,49.82,86.15,54.13,67.74,117.13,85.61,74.11,118.70,38.25,...,NaN,76.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,out/19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,nov/19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,dez/19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,jan/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,fev/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,mar/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,abr/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,mai/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,jun/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,jul/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,ago/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,set/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,out/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,nov/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,dez/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN